# Generated by Django 3.2 on 2021-05-21 11:31

from django.conf import settings
from django.db import migrations, models
import inventoryorg.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date_Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last_Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('acc_type', models.CharField(choices=[('AD', 'Admin'), ('MG', 'Manager'), ('ST', 'Staff')], default='ST', max_length=2, verbose_name='Account_Type(AD,MG,ST)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('email', models.OneToOneField(on_delete=models.SET(inventoryorg.models.get_defm), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Iemployee',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40, verbose_name='Category')),
                ('brand', models.CharField(default='Unbranded', max_length=40, verbose_name='Brand')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price')),
                ('vendor', models.CharField(default='Unknown', max_length=50, verbose_name='Vendor Name')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('is_returnable', models.BooleanField(default=True, verbose_name='Is Returnable')),
            ],
            options={
                'db_table': 'Iproduct',
            },
        ),
        migrations.CreateModel(
            name='Productlist',
            fields=[
                ('product_serial', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Product Serial Number')),
                ('status', models.CharField(choices=[('AV', 'Available'), ('UM', 'Under_Maintenance'), ('IS', 'Issued')], default='AV', max_length=2, verbose_name='Status(AV,UM,IS)')),
                ('product_id', models.ForeignKey(on_delete=models.SET(inventoryorg.models.get_def), to='inventoryorg.product')),
            ],
            options={
                'db_table': 'Iproductlist',
            },
        ),
        migrations.CreateModel(
            name='Invt_mgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(verbose_name='Issued On')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Return On')),
                ('reporting_date', models.DateTimeField(blank=True, null=True, verbose_name='Reported On')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('export_to_csv', models.BooleanField(default=False)),
                ('employee_id', models.ForeignKey(on_delete=models.SET(inventoryorg.models.get_def), to='inventoryorg.employee')),
                ('product_id', models.ForeignKey(on_delete=models.SET(inventoryorg.models.get_def), to='inventoryorg.product')),
                ('product_serial', models.ForeignKey(on_delete=models.SET(inventoryorg.models.get_def), to='inventoryorg.productlist')),
            ],
            options={
                'db_table': 'Iinvt_mgt',
            },
        ),
    ]
