# Generated by Django 3.2 on 2021-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryorg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invt_mgt',
            name='export_to_csv',
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('MG', 'Manager'), ('ST', 'Staff')], default='ST', help_text='(AD,MG,ST)', max_length=2, verbose_name='Account_Type'),
        ),
        migrations.AlterField(
            model_name='invt_mgt',
            name='remark',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('UM', 'Under_Maintenance'), ('IS', 'Issued')], default='AV', help_text='(AV, UM, IS)', max_length=2, verbose_name='Status'),
        ),
    ]
